# example config
name: Name
api:
  port: ":8085"
  secret_key: "uCPzEwGkshf"
  origin: "https://vol-3.web-almanac.com"
mongo:
  db: exampleDB
#  uri: "mongodb://root:example@localhost:27017"
  uri: "mongodb://root:a9sLUjB3tvGTH@85.192.30.210:27017"

  users:
    - login: "admin"
      password: "adminpass"
    - login: "user2"
      password: "userpass"
  collections:
    [
    "publication",
    "authors",
    "translations"
    ]
  auth:
    auth_collection: "authors"
    auth_location: "author.user"
  publication:
    fields:
      - Name: Title
        Type: "string"
        Tags: 'binding:"required"'
      - Name: Id
        Type: "int64"
        Tags: 'binding:"required"'
  authors:
    fields:
      - Name: Title
        Type: "string"
        Tags: 'binding:"required"'
      - Name: Id
        Type: "int64"
        Tags: 'binding:"required"'
      - Name: Time
        Type: "time.Time"
        Tags: 'binding:"required"'
      - Name: Author
        Type: "struct"
        Tags: 'binding:"omitempty"'
        fields:
          - Name: Name
            Type: "string"
            Tags: 'binding:"required"'
          - Name: User
            Type: "*struct"
            Tags: 'binding:"omitempty"'
            fields:
              - Name: Login
                Type: "string"
                Tags: 'binding:"omitempty"'
              - Name: Password
                Type: "string"
                Tags: 'binding:"omitempty"'
              - Name: Roles
                Type: "[]string"
                Tags: 'binding:"omitempty"'
      - Name: NilStruct
        Type: "*struct"
        Tags: 'binding:"omitempty"'
        fields:
          - Name: Name
            Type: "string"
            Tags: 'binding:"required"'
  translations:
    fields:
      - Name: Title
        Type: "string"
        Tags: 'binding:"required"'
      - Name: Id
        Type: "int64"
        Tags: 'binding:"required"'
      - Name: Author
        Type: "time.Time"
        Tags: 'binding:"omitempty"'
        fields:
          - Name: Name
            Type: "string"
            Tags: 'binding:"required"'
      - Name: NilStruct
        Type: "*struct"
        Tags: 'binding:"omitempty"'
        fields:
          - Name: Name
            Type: "string"
            Tags: 'binding:"required"'