# example config
name: Name
api:
  port: ":8085"
  secret_key: "uCPzEwGkshf"
  origin: "*"
mongo:
  db: exampleDB
  uri: "mongodb://root:example@localhost:27017"

  users:
    - login: "admin"
      password: "adminpass"
    - login: "user2"
      password: "userpass"
  collections:
    [
    "publication",
    "authors",
    "translations",
    "dictionaries"
    ]
  auth:
    auth_collection: "authors"
    auth_location: "author.user"
  dictionaries:
    fields:
      - Name: Dict
        Type: "[]struct"
        Tags: 'binding:"required,gte=1,lte=3000"'
        fields:
          - Name: GifTag
            Type: "string"
            Tags: 'binding:"required"'
          - Name: Meaning
            Type: "string"
            Tags: 'binding:"required"'
      - Name: AuthorId
        Type: "string"
        Tags: 'binding:"required,gte=1,lte=30"'
  publication:
    fields:
      - Name: Title
        Type: "string"
        Tags: 'binding:"required"'
      - Name: Id
        Type: "int64"
        Tags: 'binding:"required"'
      - Name: Map
        Type: "map[string]string"
        Tags: 'binding:"required"'
  authors:
    fields:
      - Name: Title
        Type: "string"
        Tags: 'binding:"required"'
      - Name: Id
        Type: "int64"
        Tags: 'binding:"required"'
      - Name: Time
        Type: "time.Time"
        Tags: 'binding:"required"'
      - Name: Author
        Type: "struct"
        Tags: 'binding:"omitempty"'
        fields:
          - Name: Name
            Type: "string"
            Tags: 'binding:"required"'
          - Name: User
            Type: "*struct"
            Tags: 'binding:"omitempty"'
            fields:
              - Name: Login
                Type: "string"
                Tags: 'binding:"omitempty"'
              - Name: Password
                Type: "string"
                Tags: 'binding:"omitempty"'
              - Name: Roles
                Type: "[]string"
                Tags: 'binding:"omitempty"'
      - Name: NilStruct
        Type: "*struct"
        Tags: 'binding:"omitempty"'
        fields:
          - Name: Name
            Type: "string"
            Tags: 'binding:"required"'
  translations:
    fields:
      - Name: Title
        Type: "string"
        Tags: 'binding:"required"'
      - Name: Id
        Type: "int64"
        Tags: 'binding:"required"'
      - Name: Author
        Type: "time.Time"
        Tags: 'binding:"omitempty"'
        fields:
          - Name: Name
            Type: "string"
            Tags: 'binding:"required"'
      - Name: NilStruct
        Type: "*struct"
        Tags: 'binding:"omitempty"'
        fields:
          - Name: Name
            Type: "string"
            Tags: 'binding:"required"'