# example config
name: Name
api:
  port: ":8080"
  secret_key: "uCPzEwGkshf"
  origin: "*"
mongo:
  db: exampleDB

  users:
    - login: "admin"
      password: "adminpass"
      roles: ["*"]
    - login: "user_can_delete"
      password: "adminpass"
      roles: ["delete dictionaries"]
    - login: "user_can_get"
      password: "adminpass"
      roles: ["get dictionaries"]
    - login: "user_with_nil"
      password: "adminpass"
    - login: "user_with_empty"
      password: "adminpass"
      roles: []
  collections:
    [
    "publication",
    "authors",
    "translations",
    "dictionaries"
    ]
  dictionaries:
    necessary_auth_role:
      post: "post dictionaries"
      put: "put dictionaries"
      get: "get dictionaries"
      delete: "delete dictionaries"
    fields:
      - Name: Dict
        Type: "[]struct"
        Tags: 'binding:"required,gte=1,lte=3000"'
        fields:
          - Name: GifTag
            Type: "string"
            Tags: 'binding:"required"'
          - Name: Meaning
            Type: "string"
            Tags: 'binding:"required"'
      - Name: AuthorId
        Type: "string"
        Tags: 'binding:"required,gte=1,lte=30"'
  publication:
    fields:
      - Name: Title
        Type: "string"
        Tags: 'binding:"required"'
      - Name: Id
        Type: "int64"
        Tags: 'binding:"required"'
      - Name: Map
        Type: "map[string]string"
        Tags: 'binding:"required"'
  authors:
    fields:
      - Name: Title
        Type: "string"
        Tags: 'binding:"required"'
      - Name: Id
        Type: "int64"
        Tags: 'binding:"required"'
      - Name: Time
        Type: "time.Time"
        Tags: 'binding:"required"'
      - Name: Author
        Type: "struct"
        Tags: 'binding:"omitempty"'
        fields:
          - Name: Name
            Type: "string"
            Tags: 'binding:"required"'
          - Name: User
            Type: "*struct"
            Tags: 'binding:"omitempty"'
            fields:
              - Name: Login
                Type: "string"
                Tags: 'binding:"omitempty"'
              - Name: Password
                Type: "string"
                Tags: 'binding:"omitempty"'
              - Name: Roles
                Type: "[]string"
                Tags: 'binding:"omitempty"'
      - Name: NilStruct
        Type: "*struct"
        Tags: 'binding:"omitempty"'
        fields:
          - Name: Name
            Type: "string"
            Tags: 'binding:"required"'
  translations:
    fields:
      - Name: Title
        Type: "string"
        Tags: 'binding:"required"'
      - Name: Id
        Type: "int64"
        Tags: 'binding:"required"'
      - Name: Author
        Type: "time.Time"
        Tags: 'binding:"omitempty"'
        fields:
          - Name: Name
            Type: "string"
            Tags: 'binding:"required"'
      - Name: NilStruct
        Type: "*struct"
        Tags: 'binding:"omitempty"'
        fields:
          - Name: Name
            Type: "string"
            Tags: 'binding:"required"'