services:
  mongo:
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/test/data/db
    ports:
      - "27017:27017"


volumes:
  mongo-data:
    driver: local